// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "Q1.hpp"

TEST_CASE("Ex1 makeRecord() ", "[example]")
{

	Student student[100];
	int numRecords;
	ifstream ifs;
	int flag = 1;

	numRecords = makeRecords(student);
	printRecords(student, numRecords);
	INFO("The number of lines should be 10")
	REQUIRE(numRecords == 10);
	writeTop3Records(student, numRecords);
	ifs.open("output.txt");
	if (!ifs)
		flag = 0;
	INFO("The file ouput.txt should be created");
	REQUIRE(flag == 1);
}